
[functions.line-gateway]
enabled = true
verify_jwt = false
import_map = "./functions/line-gateway/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/line-gateway/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/line-gateway/*.html" ]
